/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportmanagement;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.imageio.ImageIO;
import javax.swing.*;


public class Std_Update extends javax.swing.JFrame {
Connection con=null;
Connection con1=null;
Connection con2=null;
ResultSet rs =null;
PreparedStatement pst=null;
//Statement st1;
//Statement st2;
Statement st;
public static int dep1;
public static int dep;
public static String dep2;
public static String dep3;
    /**
     * Creates new form Std_Update
     */
    public Std_Update() {
        initComponents();
        con=db.java_db();
        con1=db.java_db();
        con2=db.java_db();
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        depart();
        spo();
        jLabel3.setVisible(false);
        txt_regno.setVisible(false);
        jLabel4.setVisible(false);
        search_fname.setVisible(false);
        jLabel5.setVisible(false);
        search_lname.setVisible(false);
    }
    public void depart(){
    try{
        Statement st=con.createStatement();
        String sql="SELECT * FROM Department ";
        ResultSet rs4=st.executeQuery(sql);
        String d1;
        while(rs4.next()){
            d1=rs4.getString("dpt_name");
            depart.addItem(d1);
        }
        //rs1.close();    
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}    
    }
    public void spo(){
    try{
        Statement st=con.createStatement();
        String sql="SELECT * FROM Sport ";
        rs=st.executeQuery(sql);
        String d1;
        while(rs.next()){
            d1=rs.getString("sp_name");
            sport.addItem(d1);
        }
        //rs2.close();    
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);}    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_regno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        search_fname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        search_lname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        oname = new javax.swing.JTextField();
        sem = new javax.swing.JTextField();
        room = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        depart = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        sport = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        stid = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        dob = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUDENT SEARCH AND UPDATE FORM");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Search by:");

        combo1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registration Number", "First Name", "Last Name" }));
        combo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo1MouseClicked(evt);
            }
        });
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Registration Number:");

        txt_regno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_regnoActionPerformed(evt);
            }
        });
        txt_regno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_regnoKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("First Name:");

        search_fname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        search_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_fnameKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Last Name:");

        search_lname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        search_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_lnameActionPerformed(evt);
            }
        });
        search_lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_lnameKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Other Name:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Date Of Birth:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Department:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Semester:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Room Number:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Sport:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Email:");

        fname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameKeyTyped(evt);
            }
        });

        lname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lnameKeyTyped(evt);
            }
        });

        oname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        oname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                onameKeyTyped(evt);
            }
        });

        sem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                semKeyTyped(evt);
            }
        });

        room.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        room.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                roomKeyTyped(evt);
            }
        });

        email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Gender:");

        gender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        depart.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        depart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                departMouseClicked(evt);
            }
        });
        depart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("ID:");

        sport.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Fisrt Name:");

        stid.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        stid.setEnabled(false);
        stid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stidActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Last Name:");

        jDesktopPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Browse A Picture");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        dob.setDateFormatString("MM/dd/yyyy");
        dob.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_regno, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(combo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stid, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(oname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(room)
                                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(sport, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(search_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(38, 38, 38)
                                    .addComponent(depart, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(52, 52, 52)
                                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_regno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(stid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(oname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(depart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sem, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(room, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(sport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_lnameActionPerformed

    private void txt_regnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_regnoKeyReleased
        // TODO add your handling code here:
        try{ 
                String sql ="select * from Student where reg_no=? "; 
                pst=con.prepareStatement(sql); 
                pst.setString(1,txt_regno.getText()); 
                rs=pst.executeQuery(); 
                String add1 =rs.getString("reg_no"); 
                stid.setText(add1); 
                String add2 =rs.getString("fname"); 
                fname.setText(add2); 
                String add3 =rs.getString("lname"); 
                lname.setText(add3); 
                String add4 =rs.getString("oname"); 
                oname.setText(add4); 
                String add5 =rs.getString("dob"); 
                SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
                //SimpleDateFormat.formatter(add5);
                Date dat=formatter.parse(add5);
                dob.setDate(dat); 
                String add6 =rs.getString("depart_id");
               
                depart.setSelectedItem(add6);
                String add7 =rs.getString("semester"); 
                sem.setText(add7); 
                String add8 =rs.getString("room"); 
                room.setText(add8); 
                String add10 =rs.getString("sport_id"); 
                
                sport.setSelectedItem(add10); 
                String add11 =rs.getString("email"); 
                email.setText(add11); 
                String add12 =rs.getString("gender"); 
                gender.setSelectedItem(add12); 
                byte[] image1 = rs.getBytes("image"); 
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(image1).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH)); 
                img.setIcon(imageIcon); 
                }catch(Exception e){} 
                finally{ 
                    try{ 
                        rs.close(); 
                        pst.close(); 
                        } catch(Exception e){ } 
}
    }//GEN-LAST:event_txt_regnoKeyReleased

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
        if(combo1.getSelectedItem().equals("Registration Number")){
            jLabel3.setVisible(true);
            txt_regno.setVisible(true);
            jLabel4.setVisible(false);
            search_fname.setVisible(false);
            jLabel5.setVisible(false);
            search_lname.setVisible(false);
        }
        else if(combo1.getSelectedItem().equals("First Name")){
            jLabel3.setVisible(false);
            txt_regno.setVisible(false);
            jLabel4.setVisible(true);
            search_fname.setVisible(true);
            jLabel5.setVisible(false);
            search_lname.setVisible(false);
        }
        else if(combo1.getSelectedItem().equals("Last Name")){
            jLabel3.setVisible(false);
            txt_regno.setVisible(false);
            jLabel4.setVisible(false);
            search_fname.setVisible(false);
            jLabel5.setVisible(true);
            search_lname.setVisible(true);
        }
        
    }//GEN-LAST:event_combo1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        filename=f.getAbsolutePath();
        ImageIcon imageIcon=new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(), img.getHeight(),Image.SCALE_DEFAULT));
        img.setIcon(imageIcon);
        try{
            File image=new File(filename);
            FileInputStream fix=new FileInputStream(image);
            ByteArrayOutputStream bos=new ByteArrayOutputStream();
            byte[] buf=new byte[1024];
            for(int number;(number=fix.read(buf))!=-1;){
                bos.write(buf,0,number);
            }
            person_image=bos.toByteArray();

        }catch(Exception e)
        {
            //JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_regnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_regnoActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        SimpleDateFormat dcn=new SimpleDateFormat("MM/dd/yyyy");
        String date=dcn.format(dob.getDate());    
        String value11 = stid.getText();
            boolean status=Validate.validateEmail(email.getText());
            if(fname.getText().isEmpty() || lname.getText().isEmpty()||oname.getText().isEmpty()||sem.getText().isEmpty()||room.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Fields are empty"); }
            else
            {   
                if(status)
                { 
                try{
                //String value11 = stdid.getText(); 
                String value1 = fname.getText(); 
                String value2 = lname.getText(); 
                String value3 = oname.getText(); 
                String value4 = date; 
                int value5 = dep; 
                String value6 = sem.getText(); 
                String value7 = room.getText(); 
                int value8 = dep1; 
                String value9 = email.getText();
                String value10 = gender.getSelectedItem().toString(); 


 
                String sql="UPDATE Student SET reg_no='"+value11+"',fname='"+value1+"',lname='"+value2+"',oname='"+value3+"',"
                    +"dob='"+value4+"',depart_id='"+value5+"',semester='"+value6+"',room='"+value7+"',"
                    +"sport_id='"+value8+"',email='"+value9+"',gender='"+value10+"'"
                    +"WHERE reg_no='"+value11+"'";
                pst=con.prepareStatement(sql); 
                pst.execute();
                JOptionPane.showMessageDialog(null, "Student Updated"); 

                }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
                }
                try{
                File file= new File(filename);
                FileInputStream fis=new FileInputStream(file);
                byte[] image=new byte[(int)file.length()];
                fis.read(image);
                String sql="UPDATE Student SET image=? WHERE reg_no='"+value11+"'";
                pst=con.prepareStatement(sql);
                pst.setBytes(1,image);
                pst.executeUpdate();
                pst.close();
                }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
                }
                finally{
                try{
                    rs.close();
                    pst.close();
                }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
                }
                }
                }else{ 
                    JOptionPane.showMessageDialog(null,"Email is invalid");}
                }
            

       
    }//GEN-LAST:event_updateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{ 
            String sql ="delete from Student where reg_no=? "; 
            pst=con.prepareStatement(sql); 
            pst.setString(1, stid.getText()); 
            pst.execute(); 
            JOptionPane.showMessageDialog(null,"Record Deleted");
            stid.setText(null);
            fname.setText(null);
            lname.setText(null);
            oname.setText(null);
            email.setText(null);
            sem.setText(null);
            room.setText(null);
            img.setIcon(null);
            }catch(Exception e){ 
            JOptionPane.showMessageDialog(null, e); 
            }
            finally{ 
            try{ 
            rs.close(); 
            pst.close(); 
            }catch(Exception e){ } }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void stidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stidActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MainMenu j=new MainMenu();
        j.setVisible(true); 
        this.dispose();        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void search_fnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_fnameKeyReleased
        // TODO add your handling code here:
        try{ 
                String sql ="select * from Student where fname=? "; 
                pst=con.prepareStatement(sql); 
                pst.setString(1,search_fname.getText()); 
                rs=pst.executeQuery(); 
                String add1 =rs.getString("reg_no"); 
                stid.setText(add1); 
                String add2 =rs.getString("fname"); 
                fname.setText(add2); 
                String add3 =rs.getString("lname"); 
                lname.setText(add3); 
                String add4 =rs.getString("oname"); 
                oname.setText(add4);
                String add5 =rs.getString("dob"); 
                SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
                //SimpleDateFormat.formatter(add5);
                Date dat=formatter.parse(add5);
                dob.setDate(dat);
                String add6 =rs.getString("depart_id"); 
                depart.setSelectedItem(add6);
                String add7 =rs.getString("semester"); 
                sem.setText(add7); 
                String add8 =rs.getString("room"); 
                room.setText(add8); 
                String add10 =rs.getString("sport_id"); 
                sport.setSelectedItem(add10); 
                String add11 =rs.getString("email"); 
                email.setText(add11); 
                String add12 =rs.getString("gender"); 
                gender.setSelectedItem(add12); 
                byte[] image1 = rs.getBytes("image"); 
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(image1).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH)); 
                img.setIcon(imageIcon); 
        }catch(Exception e){} 
        finally { 
            try{ 
                rs.close(); 
                pst.close(); 
                }catch(Exception e){
                    
                }} 
        
    }//GEN-LAST:event_search_fnameKeyReleased

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void search_lnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_lnameKeyReleased
        // TODO add your handling code here:
        try{ 
                String sql ="select * from Student where lname=? "; 
                pst=con.prepareStatement(sql); 
                pst.setString(1,search_lname.getText()); 
                rs=pst.executeQuery(); 
                String add1 =rs.getString("reg_no"); 
                stid.setText(add1); 
                String add2 =rs.getString("fname"); 
                fname.setText(add2); 
                String add3 =rs.getString("lname"); 
                lname.setText(add3); 
                String add4 =rs.getString("oname"); 
                oname.setText(add4); 
                String add5 =rs.getString("dob"); 
                SimpleDateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
                //SimpleDateFormat.formatter(add5);
                Date dat=formatter.parse(add5);
                dob.setDate(dat); 
                String add6 =rs.getString("depart_id"); 
                depart.setSelectedItem(add6);
                String add7 =rs.getString("semester"); 
                sem.setText(add7); 
                String add8 =rs.getString("room"); 
                room.setText(add8); 
                String add10 =rs.getString("sport_id"); 
                sport.setSelectedItem(add10); 
                String add11 =rs.getString("email"); 
                email.setText(add11); 
                String add12 =rs.getString("gender"); 
                gender.setSelectedItem(add12); 
                byte[] image1 = rs.getBytes("image"); 
                ImageIcon imageIcon = new ImageIcon(new ImageIcon(image1).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH)); 
                img.setIcon(imageIcon); 
        }catch(Exception e){} 
        finally { 
            try{ 
                rs.close(); pst.close(); 
                } catch(Exception e){ 
                    
                }} 
    }//GEN-LAST:event_search_lnameKeyReleased

    private void fnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameKeyReleased

    private void fnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameKeyTyped
        // TODO add your handling code here:
        char s=evt.getKeyChar();
        if(Character.isLetter(s) ||Character.isWhitespace(s) )
            fname.setText(fname.getText());
        else
            evt.consume();
    }//GEN-LAST:event_fnameKeyTyped

    private void lnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameKeyTyped
        // TODO add your handling code here:
        char s=evt.getKeyChar();
        if(Character.isLetter(s) ||Character.isWhitespace(s) )
            lname.setText(lname.getText());
        else
            evt.consume();
    }//GEN-LAST:event_lnameKeyTyped

    private void onameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onameKeyTyped
        // TODO add your handling code here:
        char s=evt.getKeyChar();
        if(Character.isLetter(s) ||Character.isWhitespace(s) )
            oname.setText(oname.getText());
        else
            evt.consume();
    }//GEN-LAST:event_onameKeyTyped

    private void semKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_semKeyTyped
        // TODO add your handling code here:
        char s=evt.getKeyChar();
        if(Character.isLetter(s) ||Character.isWhitespace(s) )
            sem.setText(sem.getText());
        else
            evt.consume();
    }//GEN-LAST:event_semKeyTyped

    private void roomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomKeyTyped
        // TODO add your handling code here:
        char s=evt.getKeyChar();
        if(Character.isDigit(s))
            room.setText(room.getText());
        else
            evt.consume();
    }//GEN-LAST:event_roomKeyTyped

    private void departActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departActionPerformed
        // TODO add your handling code here:
        try{
            String d=depart.getSelectedItem().toString();
            String sql ="SELECT * FROM Department WHERE dpt_name='"+d+"' ";
            Statement st=con.createStatement();
            rs=st.executeQuery(sql);
            
            dep=rs.getInt("id");
            //JOptionPane.showMessageDialog(null, dep);
           rs.close();    
        
        }catch(Exception e){
        //JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_departActionPerformed

    private void departMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_departMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_departMouseClicked

    private void combo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo1MouseClicked
        // TODO add your handling code here: Registration Number First Name Last Name
        
        
    }//GEN-LAST:event_combo1MouseClicked

    private void sportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportActionPerformed
        // TODO add your handling code here:
        try{
            String d=sport.getSelectedItem().toString();
            String sql ="SELECT * FROM Sport WHERE sp_name='"+d+"' ";
            Statement st=con.createStatement();
            rs=st.executeQuery(sql);
            
            dep1=rs.getInt("id");
            JOptionPane.showMessageDialog(null, dep);
           rs.close();    
        
        }catch(Exception e){
        //JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_sportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Std_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Std_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Std_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Std_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Std_Update().setVisible(true);
            }
         });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> depart;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField oname;
    private javax.swing.JTextField room;
    private javax.swing.JTextField search_fname;
    private javax.swing.JTextField search_lname;
    private javax.swing.JTextField sem;
    private javax.swing.JComboBox<String> sport;
    private javax.swing.JTextField stid;
    private javax.swing.JTextField txt_regno;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
String filename=null;
byte[] person_image=null;


}
